# Generated by Django 3.1.4 on 2020-12-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importation_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('payed', models.IntegerField(default=0)),
                ('debt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImportationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importation_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImportationDetailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=14)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('importation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.importationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ImportationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=14)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('importation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.importation')),
            ],
        ),
    ]
