# Generated by Django 3.1.4 on 2020-12-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipRegistrationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner', models.IntegerField()),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.CharField(max_length=320)),
                ('is_done', models.BooleanField(default=False)),
                ('status', models.CharField(default='Đang chờ duyệt', max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership.city')),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealership.district')),
                ('type', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='dealership.dealershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='DealershipCancellationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('status', models.CharField(default='Đang chờ duyệt', max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.dealership')),
            ],
        ),
    ]
