# Generated by Django 3.1.4 on 2020-12-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DealershipType',
            fields=[
                ('id', models.CharField(editable=None, max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('maximum_number_of_dealerships', models.IntegerField()),
                ('maximum_debt', models.IntegerField(default=0)),
                ('discount_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(editable=False, max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealership.city')),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('debt', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership.city')),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealership.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.owner')),
                ('type', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='dealership.dealershiptype')),
            ],
        ),
    ]
